In [5]:
!pip install ipython-sql psycopg2

Requirement already satisfied: ipython-sql in c:\users\timwo\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: psycopg2 in c:\users\timwo\anaconda3\lib\site-packages (2.9.9)
Requirement already satisfied: prettytable in c:\users\timwo\anaconda3\lib\site-packages (from ipython-sql) (3.11.0)
Requirement already satisfied: ipython in c:\users\timwo\anaconda3\lib\site-packages (from ipython-sql) (8.15.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\timwo\anaconda3\lib\site-packages (from ipython-sql) (2.0.32)
Requirement already satisfied: sqlparse in c:\users\timwo\anaconda3\lib\site-packages (from ipython-sql) (0.5.1)
Requirement already satisfied: six in c:\users\timwo\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\timwo\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\timwo\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.7.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\timwo\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (2.0.1)
Requirement already satisfied: backcall in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: decorator in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: colorama in c:\users\timwo\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\timwo\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\timwo\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\timwo\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\timwo\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\timwo\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [6]:
%load_ext sql

displaylimit: Value None will be treated as 0 (no limit)

Deploy Panel apps for free on Ploomber Cloud! Learn more: https://ploomber.io/s/signup

In [7]:
%sql postgresql://postgres:Aces13579@localhost:5433/HBO_TV_Movies

Connecting to 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

In [8]:
%config SqlMagic.displaylimit = None;

displaylimit: Value None will be treated as 0 (no limit)

#### Selected all the columns from the credits table in the HBO Max dataset

In [18]:
%sql SELECT * FROM Public."Credits" LIMIT 20

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+-----------+----------+-------------------+----------------------------------------------------+-------+
| person_id |    id    |        name       |                     character                      |  role |
+-----------+----------+-------------------+----------------------------------------------------+-------+
|   60017   | tm155702 |    Judy Garland   |                    Dorothy Gale                    | ACTOR |
|   53496   | tm155702 |     Ray Bolger    |                  Hunk / Scarecrow                  | ACTOR |
|   79549   | tm155702 |     Jack Haley    |                 Hickory / Tin Man                  | ACTOR |
|   79548   | tm155702 |     Bert Lahr     |                Zeke / Cowardly Lion                | ACTOR |
|   60995   | tm155702 | Margaret Hamilton |      Elmira Gulch / Wicked Witch of the West       | ACTOR |
|   53493   | tm155702 |    Frank Morgan   |          Professor Marvel / Wizard of Oz           | ACTOR |
|   79551   | tm155702 |   Clara Blandick  |                     Auntie Em                      | ACTOR |
|   41661   | tm155702 |  Charley Grapewin |                    Uncle Henry                     | ACTOR |
|   72816   | tm155702 |    Billie Burke   |                       Glinda                       | ACTOR |
|   79553   | tm155702 |     Pat Walshe    |                       Nikko                        | ACTOR |
|   79554   | tm155702 |       Terry       |                        Toto                        | ACTOR |
|    6134   | tm155702 | Adriana Caselotti |            Juliet (voice) (uncredited)             | ACTOR |
|   34566   | tm155702 |    Harry Earles   |         Lollipop Guild Member (uncredited)         | ACTOR |
|   79583   | tm155702 |    Jerry Maren    |         Lollipop Guild Member (uncredited)         | ACTOR |
|   79600   | tm155702 | Parnell St. Aubin |               Munchkin (uncredited)                | ACTOR |
|   13768   | tm155702 |   Billy Bletcher  | Mayor / Lollipop Guild Member (voice) (uncredited) | ACTOR |
|    6139   | tm155702 |    Pinto Colvig   |           Munchkins (voice) (uncredited)           | ACTOR |
|   79550   | tm155702 |   Charles Becker  |            Munchkin Mayor (uncredited)             | ACTOR |
|   74888   | tm155702 |   Mitchell Lewis  |      Captain of the Winkie Guard (uncredited)      | ACTOR |
|   41687   | tm155702 |   Buster Brodie   |             Winged Monkey (uncredited)             | ACTOR |
+-----------+----------+-------------------+----------------------------------------------------+-------+

#### Selected all the columns from the titles table in the  HBO Max dataset

In [10]:
%sql Select * FROM Public."Titles" LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+----------+----------------------------------+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-------------------+---------+---------------------------------------------+----------------------+---------+------------+------------+------------+-----------------+------------+
|    id    |              title               |  type |                                                                                                                                                                                                                        description                                                                                                                                                                                                                        | release_year | age_certification | runtime |                    genres                   | production_countries | seasons |  imdb_id   | imdb_score | imdb_votes | tmdb_popularity | tmdb_score |
+----------+----------------------------------+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-------------------+---------+---------------------------------------------+----------------------+---------+------------+------------+------------+-----------------+------------+
| tm155702 |         The Wizard of Oz         | MOVIE |                                                                    Young Dorothy finds herself in a magical world where she makes friends with a lion, a scarecrow and a tin man as they make their way along the yellow brick road to talk with the Wizard and ask for the things they miss most in their lives. The Wicked Witch of the West is the only thing that could stop them.                                                                    |     1939     |         G         |   102   |            ['fantasy', 'family']            |        ['US']        |   None  | tt0032138  |    8.1     |  389774.0  |      41.442     |    7.6     |
| tm83648  |           Citizen Kane           | MOVIE |                                                                               Newspaper magnate, Charles Foster Kane is taken from his mother as a boy and made the ward of a rich industrialist. As a result, every well-meaning, tyrannical or self-destructive move he makes for the rest of his life appears in some way to be a reaction to that deeply wounding event.                                                                              |     1941     |         PG        |   119   |                  ['drama']                  |        ['US']        |   None  | tt0033467  |    8.3     |  433804.0  |      14.383     |    8.0     |
| tm77588  |            Casablanca            | MOVIE |                                                                                                                                                                In Casablanca, Morocco in December 1941, a cynical American expatriate meets a former lover, with unforeseen complications.                                                                                                                                                                |     1942     |         PG        |   102   |         ['drama', 'romance', 'war']         |        ['US']        |   None  | tt0034583  |    8.5     |  558849.0  |      20.087     |    8.2     |
| tm82363  |          The Big Sleep           | MOVIE |                                                                                                          Private Investigator Philip Marlowe is hired by wealthy General Sternwood regarding a matter involving his youngest daughter Carmen. Before the complex case is over, Marlowe sees murder, blackmail, deception, and what might be love.                                                                                                         |     1946     |        None       |   116   |            ['thriller', 'crime']            |        ['US']        |   None  | tt0038355  |    7.9     |  84494.0   |      12.911     |    7.7     |
| tm84701  |        The Maltese Falcon        | MOVIE |                                                                                                                                                     A private detective takes on a case that involves him with three eccentric criminals, a beautiful liar, and their quest for a priceless statuette.                                                                                                                                                    |     1941     |        None       |   100   |       ['thriller', 'romance', 'crime']      |        ['US']        |   None  | tt0033870  |    8.0     |  156603.0  |      12.788     |    7.8     |
| tm156463 |        Gone with the Wind        | MOVIE |                                                                                                          The spoiled daughter of a well-to-do plantation owner is forced to use every means at her disposal to claw her way out of poverty, following Maj. Gen. William Sherman's destructive "March to the Sea,” during the American Civil War.                                                                                                          |     1939     |         G         |   233   |    ['war', 'romance', 'drama', 'history']   |        ['US']        |   None  | tt0031381  |    8.2     |  309856.0  |      24.092     |    8.0     |
| ts225761 |          Tom and Jerry           |  SHOW |                           Tom and Jerry is an American animated franchise and series of comedy short films created in 1940 by William Hanna and Joseph Barbera. Best known for its 161 theatrical short films by Metro-Goldwyn-Mayer, the series centers on a friendship/rivalry (a love-hate relationship) between the title characters Tom, a cat, and Jerry, a mouse. Many shorts also feature several recurring characters.                           |     1940     |        None       |    8    | ['animation', 'comedy', 'family', 'action'] |        ['US']        |   16.0  | tt12158994 |    7.7     |   853.0    |       1.4       |    10.0    |
|  tm5094  | The Treasure of the Sierra Madre | MOVIE |                                 Fred C. Dobbs and Bob Curtin, both down on their luck in Tampico, Mexico in 1925, meet up with a grizzled prospector named Howard and decide to join with him in search of gold in the wilds of central Mexico. Through enormous difficulties, they eventually succeed in finding gold, but bandits, the elements, and most especially greed threaten to turn their success into disaster.                                |     1948     |        None       |   126   |             ['western', 'drama']            |        ['US']        |   None  | tt0040897  |    8.2     |  122971.0  |      14.006     |    8.0     |
| tm54459  |        The Asphalt Jungle        | MOVIE |                                                                                                                   Recently paroled from prison, legendary burglar "Doc" Riedenschneider, with funding from Alonzo Emmerich, a crooked lawyer, gathers a small group of veteran criminals together in the Midwest for a big jewel heist.                                                                                                                   |     1950     |        None       |   112   |        ['drama', 'thriller', 'crime']       |        ['US']        |   None  | tt0042208  |    7.8     |  26557.0   |      9.809      |    7.5     |
| tm81960  |      The Philadelphia Story      | MOVIE |                                                                                                                              When a rich woman's ex-husband and a tabloid-type reporter turn up just before her planned remarriage, she begins to learn the truth about herself. Remade as a musical in 1956 as High Society.                                                                                                                             |     1940     |        None       |   113   |            ['romance', 'comedy']            |        ['US']        |   None  | tt0032904  |    7.9     |  68337.0   |      11.587     |    7.7     |
| tm58806  |             Rashomon             | MOVIE |                                             Brimming with action while incisively examining the nature of truth, "Rashomon" is perhaps the finest film ever to investigate the philosophy of justice. Through an ingenious use of camera and flashbacks, Kurosawa reveals the complexities of human nature as four people recount different versions of the story of a man's murder and the rape of his wife.                                             |     1950     |        None       |    88   |              ['drama', 'crime']             |        ['JP']        |   None  | tt0042876  |    8.2     |  165278.0  |      11.33      |    8.2     |
|  tm4707  |          The Red Shoes           | MOVIE |        In this classic drama, Vicky Page is an aspiring ballerina torn between her dedication to dance and her desire to love. While her imperious instructor, Boris Lermontov, urges to her to forget anything but ballet, Vicky begins to fall for the charming young composer Julian Craster. Eventually Vicky, under great emotional stress, must choose to pursue either her art or her romance, a decision that carries serious consequences.       |     1948     |        None       |   133   |        ['romance', 'drama', 'music']        |        ['GB']        |   None  | tt0040725  |    8.1     |  34367.0   |      9.378      |    8.1     |
| tm160494 |            Stagecoach            | MOVIE |                                                                                                                                                 A group of people traveling on a stagecoach find their journey complicated by the threat of Geronimo, and learn something about each other in the process.                                                                                                                                                |     1939     |        None       |    96   |             ['western', 'drama']            |        ['US']        |   None  | tt0031971  |    7.8     |  48149.0   |      11.786     |    7.7     |
| tm47834  |                M                 | MOVIE |   In this classic German thriller, Hans Beckert, a serial killer who preys on children, becomes the focus of a massive Berlin police manhunt. Beckert's heinous crimes are so repellant and disruptive to city life that he is even targeted by others in the seedy underworld network. With both cops and criminals in pursuit, the murderer soon realizes that people are on his trail, sending him into a tense, panicked attempt to escape justice.   |     1931     |       PG-13       |   117   |      ['thriller', 'european', 'crime']      |        ['DE']        |   None  | tt0022100  |    8.3     |  155068.0  |      9.165      |    8.1     |
|  tm3248  |              Freaks              | MOVIE |                                                                                                                                           A circus' beautiful trapeze artist agrees to marry the leader of side-show performers, but his deformed friends discover she is only marrying him for his inheritance.                                                                                                                                          |     1932     |        None       |    62   |             ['drama', 'horror']             |        ['US']        |   None  | tt0022913  |    7.9     |  45726.0   |      8.294      |    7.8     |
| tm72527  |        The Great Dictator        | MOVIE |                                                                                                                                                               Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.                                                                                                                                                              |     1940     |        None       |   125   |          ['comedy', 'war', 'drama']         |        ['US']        |   None  | tt0032553  |    8.4     |  219871.0  |      15.335     |    8.4     |
|  tm2346  |           The 39 Steps           | MOVIE |                                                                                 Richard Hanney has a rude awakening when a glamorous female spy falls into his bed -- with a knife in her back. Having a bit of trouble explaining it all to Scotland Yard, he heads for the hills of Scotland to try to clear his name by locating the spy ring known as "The 39 Steps."                                                                                 |     1935     |        None       |    86   |            ['thriller', 'crime']            |        ['GB']        |   None  | tt0026029  |    7.6     |  56259.0   |      10.794     |    7.4     |
|  tm8232  |        The Lady Vanishes         | MOVIE | On a train headed for England a group of travelers is delayed by an avalanche. Holed up in a hotel in a fictional European country, young Iris befriends elderly Miss Froy. When the train resumes, Iris suffers a bout of unconsciousness and wakes to find the old woman has disappeared. The other passengers ominously deny Miss Froy ever existed, so Iris begins to investigate with another traveler and, as the pair sleuth, romantic sparks fly. |     1938     |        None       |    96   |                 ['thriller']                |        ['GB']        |   None  | tt0030341  |    7.8     |  51847.0   |       9.64      |    7.5     |
|  tm5608  |         Bicycle Thieves          | MOVIE |                                                                                                                                                                                         A working man's livelihood is threatened when someone steals his bicycle.                                                                                                                                                                                         |     1948     |        None       |    88   |            ['drama', 'european']            |        ['IT']        |   None  | tt0040522  |    8.3     |  160558.0  |      12.024     |    8.3     |
| tm45502  |         Gentleman's Fate         | MOVIE |                                                                                                                                                                                                     A bootlegger falls apart when his wife leaves him.                                                                                                                                                                                                    |     1931     |        None       |    90   |              ['crime', 'drama']             |        ['US']        |   None  | tt0021906  |    6.4     |   805.0    |      0.893      |    5.0     |
+----------+----------------------------------+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-------------------+---------+---------------------------------------------+----------------------+---------+------------+------------+------------+-----------------+------------+

#### Selected the top 20 tv shows by imdb score

In [24]:
%%sql SELECT title as tv_show, imdb_score
FROM Public."Titles"
WHERE seasons != 'None'
AND imdb_score IS NOT NULL
ORDER BY imdb_score DESC
LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+------------------------------------+------------+
|              tv_show               | imdb_score |
+------------------------------------+------------+
|          Band of Brothers          |    9.4     |
|             Chernobyl              |    9.4     |
|               Lamput               |    9.3     |
|              The Wire              |    9.3     |
|         Eyes on the Prize          |    9.2     |
|          Game of Thrones           |    9.2     |
|           Rick and Morty           |    9.2     |
|            The Sopranos            |    9.2     |
|  Fullmetal Alchemist: Brotherhood  |    9.1     |
|        The World Between Us        |    9.0     |
|             DEATH NOTE             |    9.0     |
|    Batman: The Animated Series     |    9.0     |
|          Hunter x Hunter           |    9.0     |
|              Shadows               |    8.9     |
|      Joe Pera Talks With You       |    8.9     |
|           Nathan For You           |    8.9     |
| Last Week Tonight with John Oliver |    8.9     |
|           The West Wing            |    8.9     |
|        Pride and Prejudice         |    8.9     |
|           True Detective           |    8.9     |
+------------------------------------+------------+

####  Selected the top 20 tv shows by tmdb popularity that were released in the 21st century

In [140]:
%%sql SELECT title as tv_show, ROUND(CAST(tmdb_popularity AS DECIMAL),2) as tmdb_popularity
FROM Public."Titles"
WHERE seasons is NULL
AND tmdb_popularity IS NOT NULL
AND release_year BETWEEN 2000 AND 2022
ORDER BY tmdb_popularity DESC
LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+--------------------------------------------+-----------------+
|                  tv_show                   | tmdb_popularity |
+--------------------------------------------+-----------------+
|                 The Batman                 |     4447.89     |
|          The Matrix Resurrections          |      641.54     |
|                    Kimi                    |      565.89     |
|               The King's Man               |      559.09     |
|                  Free Guy                  |      398.52     |
|             Death on the Nile              |      386.01     |
|               Mortal Kombat                |      366.71     |
|             The Suicide Squad              |      345.90     |
|              Nightmare Alley               |      342.80     |
|                  Antlers                   |      315.57     |
|                     F9                     |      305.68     |
|                    Dune                    |      301.89     |
|        Zack Snyder's Justice League        |      288.08     |
|    Harry Potter and the Goblet of Fire     |      278.20     |
|             Godzilla vs. Kong              |      274.88     |
|   The Conjuring: The Devil Made Me Do It   |      263.56     |
| Deathstroke: Knights & Dragons - The Movie |      251.69     |
|                  The Help                  |      250.49     |
|              Ron's Gone Wrong              |      242.82     |
|          Space Jam: A New Legacy           |      235.83     |
+--------------------------------------------+-----------------+

#### Selected the top 20 tv shows by tmdb score

In [141]:
%%sql SELECT title as tv_show, tmdb_score
FROM Public."Titles"
WHERE seasons IS NOT NULL
AND tmdb_score IS NOT NULL
AND tmdb_score = 10.0
ORDER BY tmdb_score DESC
LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+----------------------------------+------------+
|             tv_show              | tmdb_score |
+----------------------------------+------------+
|          Tom and Jerry           |    10.0    |
|             Autopsy              |    10.0    |
|             Crashbox             |    10.0    |
| Category 7: The End of the World |    10.0    |
|          Classical Baby          |    10.0    |
|         Little Baby Bum          |    10.0    |
|            Dios Inc.             |    10.0    |
|       Secret Life of Lakes       |    10.0    |
|     Secret Life Underground      |    10.0    |
|       The History of Food        |    10.0    |
|     Talk Show the Game Show      |    10.0    |
|        Forensic Files II         |    10.0    |
|            Craftopia             |    10.0    |
|       Detention Adventure        |    10.0    |
| The Not-Too-Late Show with Elmo  |    10.0    |
|              Julia               |    10.0    |
|        Trinity of Shadows        |    10.0    |
|            On the Job            |    10.0    |
|           Sandy + Chef           |    10.0    |
|           Os Ausentes            |    10.0    |
+----------------------------------+------------+

#### Selected the top 20 tv shows by the most imdb votes

In [142]:
%%sql SELECT title as tv_show, ROUND(MAX(imdb_votes)) as highest_votes
FROM Public."Titles"
WHERE seasons IS NOT NULL
GROUP BY tv_show
HAVING MAX(imdb_votes) IS NOT NULL
ORDER BY highest_votes DESC
LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+---------------------+---------------+
|       tv_show       | highest_votes |
+---------------------+---------------+
|   Game of Thrones   |    1983794    |
|       Friends       |     950362    |
| The Big Bang Theory |     782154    |
|      Chernobyl      |     693955    |
|    True Detective   |     546443    |
|      Westworld      |     474807    |
|    Rick and Morty   |     473951    |
|   Band of Brothers  |     440706    |
|     The Sopranos    |     372367    |
|      South Park     |     359621    |
|       The Wire      |     325150    |
|      DEATH NOTE     |     302147    |
|        Fringe       |     236555    |
|      Doctor Who     |     218162    |
|   Boardwalk Empire  |     184970    |
|   Big Little Lies   |     184531    |
|    The Mentalist    |     179569    |
|  Person of Interest |     172971    |
|     Gossip Girl     |     167534    |
|         Rome        |     167119    |
+---------------------+---------------+

#### Wrote a query to determine the  number of directors who directed movies that received an imdb score of 9.0 or higher

In [137]:
%%sql SELECT role, name, title AS movie, imdb_score
FROM Public."Credits"
INNER JOIN Public."Titles"
ON Public."Credits".id = Public."Titles".id
WHERE imdb_score IS NOT NULL
AND role = 'DIRECTOR'
AND seasons IS NULL
AND imdb_score IS NOT NULL
AND imdb_score >= 9.0
ORDER BY 4 DESC

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

4 rows affected.

+----------+---------------------+-----------------------------------------------+------------+
|   role   |         name        |                     movie                     | imdb_score |
+----------+---------------------+-----------------------------------------------+------------+
| DIRECTOR |    Frank Darabont   |            The Shawshank Redemption           |    9.3     |
| DIRECTOR |  Christopher Nolan  |                The Dark Knight                |    9.0     |
| DIRECTOR |    Peter Jackson    | The Lord of the Rings: The Return of the King |    9.0     |
| DIRECTOR | Jean Gabriel Guerra |  Juan Luis Guerra 4.40: Entre Mar y Palmeras  |    9.0     |
+----------+---------------------+-----------------------------------------------+------------+

#### Selected the top 20 movies by tmdb score

In [133]:
%%sql SELECT title as movie, tmdb_score
FROM Public."Titles"
WHERE seasons IS NULL
AND tmdb_score IS NOT NULL
ORDER BY tmdb_score DESC
LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+--------------------------------------------------------------+------------+
|                            movie                             | tmdb_score |
+--------------------------------------------------------------+------------+
|                      A Storybook Ending                      |    10.0    |
|             Euphoria: Trouble Don't Last Always              |    10.0    |
|                           Netizens                           |    10.0    |
|      Carole King & James Taylor: Just Call Out My Name       |    10.0    |
|          Euphoria: F*ck Anyone Who’s Not A Sea Blob          |    10.0    |
|           Goodnight Moon & Other Sleepytime Tales            |    10.0    |
|           Furry Friends Forever: Elmo Gets a Puppy           |    10.0    |
|                   Reign of the Superwomen                    |    10.0    |
|              Mike Mulligan and His Steam Shovel              |    10.0    |
|                    American Revolution 2                     |    10.0    |
|  Santana: Corazón Live from Mexico  - Live It To Believe It  |    10.0    |
|           Shakira in Concert: El Dorado World Tour           |    10.0    |
|           Legendary Nights: The Tale of Gatti-Ward           |    10.0    |
|                         Habla Women                          |    9.5     |
|                 Blade Runner: The Final Cut                  |    9.0     |
|                        The Dark Horse                        |    9.0     |
|                            First                             |    9.0     |
|                          Miniverse                           |    9.0     |
| Foster's Home for Imaginary Friends: Destination Imagination |    9.0     |
|       I Have Tourette's But Tourette's Doesn't Have Me       |    9.0     |
+--------------------------------------------------------------+------------+

#### Selected the top 20 movies by imdb score

In [136]:
%%sql SELECT title as movie, imdb_score
FROM Public."Titles"
WHERE seasons IS NULL
AND imdb_score IS NOT NULL
ORDER BY imdb_score DESC
LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+----------------------------------------------------------------------------+------------+
|                                   movie                                    | imdb_score |
+----------------------------------------------------------------------------+------------+
|                          The Shawshank Redemption                          |    9.3     |
|                             Emergency Contact                              |    9.2     |
|                              The Dark Knight                               |    9.0     |
|                    Euphoria: Trouble Don't Last Always                     |    9.0     |
|               The Lord of the Rings: The Return of the King                |    9.0     |
|                Juan Luis Guerra 4.40: Entre Mar y Palmeras                 |    9.0     |
|             The Lord of the Rings: The Fellowship of the Ring              |    8.8     |
|                    Dave Chappelle: Killin' Them Softly                     |    8.8     |
|                   The Lord of the Rings: The Two Towers                    |    8.8     |
|                                 Inception                                  |    8.8     |
|                 Euphoria: F*ck Anyone Who’s Not A Sea Blob                 |    8.8     |
|                                 The Matrix                                 |    8.7     |
| The Music in Me: The Leopards Take Manhattan - The Little Band That Roared |    8.7     |
|                     George Carlin: Jammin' in New York                     |    8.7     |
|                      One Flew Over the Cuckoo's Nest                       |    8.7     |
|                                 GoodFellas                                 |    8.7     |
|                              Celebrity Habla                               |    8.7     |
|                               The Green Mile                               |    8.6     |
|              We Stand Alone Together: The Men of Easy Company              |    8.6     |
|                                City of God                                 |    8.6     |
+----------------------------------------------------------------------------+------------+

#### Selected the top 20 movies by the most imdb votes

In [143]:
%%sql SELECT title as movie, ROUND(MAX(imdb_votes)) as highest_votes
FROM Public."Titles"
WHERE seasons IS NULL
GROUP BY title
HAVING MAX(imdb_votes) IS NOT NULL
ORDER BY highest_votes DESC
LIMIT 20;

Running query in 'postgresql://postgres:***@localhost:5433/HBO_TV_Movies'

20 rows affected.

+---------------------------------------------------+---------------+
|                       movie                       | highest_votes |
+---------------------------------------------------+---------------+
|                  The Dark Knight                  |    2555504    |
|              The Shawshank Redemption             |    2548100    |
|                     Inception                     |    2268288    |
|                     The Matrix                    |    1857949    |
| The Lord of the Rings: The Fellowship of the Ring |    1798012    |
|   The Lord of the Rings: The Return of the King   |    1776725    |
|       The Lord of the Rings: The Two Towers       |    1604677    |
|                       Se7en                       |    1586065    |
|                   Batman Begins                   |    1426616    |
|                    The Departed                   |    1283897    |
|                   The Green Mile                  |    1256927    |
|                      Memento                      |    1205770    |
|                       Joker                       |    1190053    |
|                     GoodFellas                    |    1113695    |
|                   V for Vendetta                  |    1097898    |
|                 Kill Bill: Vol. 1                 |    1082449    |
|             Terminator 2: Judgment Day            |    1067733    |
|                  The Truman Show                  |    1036001    |
|                   Reservoir Dogs                  |     989119    |
|                    The Shining                    |     984610    |
+---------------------------------------------------+---------------+